# Generated by Django 4.1.5 on 2023-02-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kpi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
