# Generated by Django 4.1.7 on 2023-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0002_alter_clickorder_options_clickorder_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickorder',
            name='transaction_external_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
