# Generated by Django 4.1.7 on 2023-04-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0003_alter_clickorder_transaction_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickorder',
            name='transaction_external_id',
        ),
    ]
