# Generated by Django 4.1.7 on 2023-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0004_remove_clickorder_transaction_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
