# Generated by Django 4.1.7 on 2023-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0005_alter_clickorder_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='clickorder',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qabul qilinadigan chora'),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='click_paydoc_id',
            field=models.CharField(blank=True, max_length=255, verbose_name="CLICK tizimidagi to'lov raqami"),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='extra_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clickorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9, verbose_name="To'lov miqdori (so'mda)"),
        ),
        migrations.AlterField(
            model_name='clickorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('processing', 'processing'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('error', 'error')], default='waiting', max_length=25, verbose_name='Holat'),
        ),
    ]
