# Generated by Django 4.1.7 on 2023-04-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0006_alter_clickorder_options_remove_clickorder_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickorder',
            options={'verbose_name': 'ClickOrder', 'verbose_name_plural': 'ClickOrders'},
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='action',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='click_paydoc_id',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='clickorder',
            name='modified',
        ),
        migrations.AddField(
            model_name='clickorder',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='transaction_external_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='clickorder',
            name='transaction_type',
            field=models.CharField(choices=[('click', 'Click')], default='imezone.now', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clickorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='new', max_length=10),
        ),
    ]
