# Generated by Django 4.1.7 on 2023-04-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0008_alter_clickorder_options_remove_clickorder_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickOrder',
        ),
    ]
