# Generated by Django 4.1.7 on 2023-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0009_delete_clickorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickorders',
            name='transaction_type',
            field=models.CharField(choices=[('click', 'Click')], default='click', max_length=10),
        ),
    ]
