# Generated by Django 4.1.5 on 2023-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=1, max_length=1000, verbose_name='Joylashuv'),
            preserve_default=False,
        ),
    ]
