# Generated by Django 4.1.5 on 2023-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforhelp',
            name='email',
            field=models.CharField(default='erkin@gamil.com', max_length=100, verbose_name='Elektron manzil'),
            preserve_default=False,
        ),
    ]
