# Generated by Django 4.1.7 on 2023-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='vendor_code',
            new_name='number',
        ),
    ]
