# Generated by Django 4.1.7 on 2023-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='k_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='warehouse',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
