# Generated by Django 4.1.7 on 2023-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
