# Generated by Django 4.1.7 on 2023-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='available_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant/'),
        ),
    ]
