# Generated by Django 4.1.7 on 2023-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_variant_rename_vendor_code_orderitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
