# Generated by Django 4.1.7 on 2023-04-10 15:32

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_category_image_ru_category_image_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.FloatField(blank=True, null=True, verbose_name='Jami narx'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone1',
            field=models.CharField(default='+998971236987', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Umumiy maxsulot narxi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=18),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_delivery',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.delivery', verbose_name='Yetkazib berish turi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeliveryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.delivery')),
            ],
            options={
                'verbose_name': 'delivery Translation',
                'db_table': 'main_delivery_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
