# Generated by Django 4.1.5 on 2023-02-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_product_alter_categorytranslation_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogTranslation',
        ),
    ]
