# Generated by Django 4.1.7 on 2023-03-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='code',
            new_name='payme_code',
        ),
    ]
