# Generated by Django 4.1.7 on 2023-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delivery_remove_order_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
