# Generated by Django 4.1.7 on 2023-03-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_code_payment_payme_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Warehouse',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.warehouses'),
        ),
    ]
