# Generated by Django 4.1.7 on 2023-04-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_province_alter_order_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province'},
        ),
    ]
