# Generated by Django 4.1.5 on 2023-02-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='productsize',
        ),
    ]
