# Generated by Django 4.1.7 on 2023-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitem_warehouse_alter_warehouses_w_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='warehouse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Warehouses',
        ),
    ]
