# Generated by Django 4.1.5 on 2023-02-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
