# Generated by Django 4.1.5 on 2023-02-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_payment_orderitem_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_per_product',
        ),
    ]
