# Generated by Django 4.1.5 on 2023-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_price_orderitem_price_per_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=10, verbose_name='Shotuv kodi'),
        ),
    ]
